# Generated by Django 2.1 on 2018-08-24 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=500)),
                ('datetime', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=50000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=500)),
                ('phone_desc1', models.CharField(max_length=10000)),
                ('phone_desc2', models.CharField(max_length=10000)),
                ('phone_desc3', models.CharField(max_length=10000)),
                ('phone_desc4', models.CharField(max_length=10000)),
                ('phone_picture', models.CharField(max_length=1000)),
                ('release_date', models.CharField(max_length=500)),
                ('dimensions', models.CharField(max_length=500)),
                ('primary_camera', models.CharField(max_length=50)),
                ('secondary_camera', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=1000)),
                ('battery', models.CharField(max_length=200)),
                ('water_resistant', models.BooleanField()),
            ],
        ),
    ]
